import axiosInstance from '../axios';

export interface IPoCode {
  id: number;
  po_header_id: number;
  item_id: number;
  rfid_code: string;
  serial_start?: string | number | null;
  serial_end?: string | number | null;
  quantity?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface CreatePoCodeData {
  po_header_id: number;
  item_id: number;
  rfid_code: string;
  serial_start?: string | number | null;
  serial_end?: string | number | null;
  quantity?: number | null;
}

export interface UpdatePoCodeData {
  po_header_id?: number;
  item_id?: number;
  rfid_code?: string;
  serial_start?: string | number | null;
  serial_end?: string | number | null;
  quantity?: number | null;
}

export interface PoCodeQueryParams {
  po_header_id?: number;
  item_id?: number;
  rfid_code?: string;
  limit?: number;
  offset?: number;
}

export interface PoCodeListResponse {
  success: boolean;
  message: string;
  data: IPoCode[];
  meta?: {
    total: number;
    limit?: number;
    offset?: number;
  };
}

export interface PoCodeResponse {
  success: boolean;
  message: string;
  data: IPoCode;
}

// Generate a 16-digit hex code
const generateHexCode = (): string => {
  // Generate 16 hex characters (8 bytes = 16 hex digits)
  const hexChars = '0123456789ABCDEF';
  let hexCode = '';
  for (let i = 0; i < 16; i++) {
    hexCode += hexChars.charAt(Math.floor(Math.random() * hexChars.length));
  }
  return hexCode;
};

export const poCodesApi = {
  // Get all PO codes with pagination and filtering
  getAll: async (params: PoCodeQueryParams = {}): Promise<PoCodeListResponse> => {
    try {
      const queryParams = new URLSearchParams();
      
      if (params.po_header_id) {
        queryParams.append('po_header_id', params.po_header_id.toString());
      }
      if (params.item_id) {
        queryParams.append('item_id', params.item_id.toString());
      }
      if (params.rfid_code) {
        queryParams.append('rfid_code', params.rfid_code);
      }
      if (params.limit) {
        queryParams.append('limit', params.limit.toString());
      }
      if (params.offset) {
        queryParams.append('offset', params.offset.toString());
      }

      const queryString = queryParams.toString();
      const endpoint = `/po-codes${queryString ? `?${queryString}` : ''}`;
      
      const response = await axiosInstance.get<PoCodeListResponse>(endpoint);
      return response.data;
    } catch (error: any) {
      console.error('Error fetching PO codes:', error);
      throw new Error(error.response?.data?.message || 'Failed to fetch PO codes');
    }
  },

  // Get single PO code by ID
  getById: async (id: number): Promise<IPoCode> => {
    try {
      const response = await axiosInstance.get<PoCodeResponse>(`/po-codes/${id}`);
      return response.data.data;
    } catch (error: any) {
      console.error('Error fetching PO code:', error);
      throw new Error(error.response?.data?.message || 'Failed to fetch PO code');
    }
  },

  // Create new PO code (RFID will be auto-generated by backend)
  create: async (data: Omit<CreatePoCodeData, 'rfid_code'>): Promise<IPoCode> => {
    try {
      // Backend will auto-generate the RFID code
      const payload: Omit<CreatePoCodeData, 'rfid_code'> = {
        po_header_id: data.po_header_id,
        item_id: data.item_id,
        serial_start: data.serial_start,
        serial_end: data.serial_end,
        quantity: data.quantity,
      };

      const response = await axiosInstance.post<PoCodeResponse>('/po-codes', payload);
      return response.data.data;
    } catch (error: any) {
      console.error('Error creating PO code:', error);
      throw new Error(error.response?.data?.message || 'Failed to create PO code');
    }
  },

  // Update PO code
  update: async (id: number, data: UpdatePoCodeData): Promise<IPoCode> => {
    try {
      const response = await axiosInstance.put<PoCodeResponse>(`/po-codes/${id}`, data);
      return response.data.data;
    } catch (error: any) {
      console.error('Error updating PO code:', error);
      throw new Error(error.response?.data?.message || 'Failed to update PO code');
    }
  },

  // Delete PO code
  delete: async (id: number): Promise<void> => {
    try {
      await axiosInstance.delete(`/po-codes/${id}`);
    } catch (error: any) {
      console.error('Error deleting PO code:', error);
      throw new Error(error.response?.data?.message || 'Failed to delete PO code');
    }
  },

  // Helper to generate hex code
  generateHexCode,
};
